---
title: "Lepetit"
author: "Eliot Lepetit"
format: html
---


```{r}
#| message: false
here::i_am("lab-grades.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)

theme_set(theme_bw())
```

1) Loading the dataset
```{r}
#| message: false
grades <- vroom(here("grades.csv"))
```


2) The data set contains `r nrow(grades)` grades.


3) 

```{r}
num_students <- grades |> 
  distinct(id) |>
  nrow()
```

There are  `r num_students` students

4)
```{r}
students <- grades |> 
  select(id, group) |>
  distinct(id, group)
```

```{r}
students |>
  slice_tail(n = 5) |>
  knitr::kable()
```


5) 

```{r}
students_per_group <- students |> 
  group_by(group) |> 
  summarise(num_students = n())
```

```{r}
ggplot(students_per_group, aes(x = group, y = num_students)) +
  geom_col() +
  geom_text(aes(label = num_students), vjust = -0.5) +  # Adds number on top of each bar
  labs(
    title = "Number of Students per Group",
    x = "Group",
    y = "Number of Students"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

